const examples = [
  {value: './lesson01/', label: 'Lesson 01: Bootstrap Grid System', style: './lesson01/style'},
  {value: './lesson02/', label: 'Lesson 02: Boxes', style: './lesson01/style'},
  {value: './lesson03/', label: 'Lesson 03: Columns', style: './lesson01/style'},
  {value: './lesson04/', label: 'Lesson 04: Column Offset', style: './lesson01/style'},
  {value: './lesson05/', label: 'Lesson 05: Row Columns', style: './lesson01/style'},
  {value: './lesson06/', label: 'Lesson 06: Row Columns Gaps', style: './lesson01/style'},
  {value: './lesson07/', label: 'Lesson 07: Tables', style: './lesson01/style'},
  {value: './lesson08/', label: 'Lesson 08: Forms', style: './lesson01/style'},
  {value: './lesson09/', label: 'Lesson 09: Select Combo', style: './lesson01/style'},
  {value: './lesson10/', label: 'Lesson 10: Checkbox', style: './lesson01/style'},
  {value: './lesson11/', label: 'Lesson 11: Input Group', style: './lesson01/style'},
  {value: './lesson12/', label: 'Lesson 12: Floating Labels', style: './lesson01/style'},
  {value: './lesson13/', label: 'Lesson 13: Button', style: './lesson01/style'},
  {value: './lesson14/', label: 'Lesson 14: Alert', style: './lesson01/style'},
  {value: './lesson15/', label: 'Lesson 15: Card', style: './lesson01/style'},
  {value: './lesson16/', label: 'Lesson 16: Modal', style: './lesson01/style'},
  {value: './lesson17/', label: 'Lesson 17: Collapse', style: './lesson01/style'},
  {value: './lesson18/', label: 'Lesson 18: Nav Bar', style: './lesson01/style'},
  {value: './lesson19/', label: 'Lesson 19: Background Colours', style: './lesson01/style'},
  {value: './lesson20/', label: 'Lesson 20: Stack', style: './lesson01/style'},
  {value: './lesson21/', label: 'Lesson 21: Border Utilities', style: './lesson01/style'},
  {value: './lesson22/', label: 'Lesson 22: Display', style: './lesson01/style'},
  {value: './lesson23/', label: 'Lesson 23: Spacing', style: './lesson01/style'},
  {value: './lesson24/', label: 'Lesson 24: Flexbox', style: './lesson01/style'},
];
