const examples = [
  {value: './01_lesson/', label: 'Lesson 01: What is CSS?'},
  {value: './02_lesson/', label: 'Lesson 02: CSS Selectors'},
  {value: './03_lesson/', label: 'Lesson 03: CSS Colors'},
  {value: './04_lesson/', label: 'Lesson 04: CSS Units'},
  {value: './05_lesson/', label: 'Lesson 05: CSS Box Model'},
  {value: './06_lesson/', label: 'Lesson 06: CSS Typography'},
  {value: './07_lesson/', label: 'Lesson 07: CSS Links'},
  {value: './08_lesson/', label: 'Lesson 08: CSS Lists'},
  {value: './09_lesson/', label: 'Lesson 09: CSS Menu'},
  {value: './10_lesson/', label: 'Lesson 10: CSS Display'},
  {value: './11_lesson/', label: 'Lesson 11: CSS Floats'},
  {value: './12_lesson/', label: 'Lesson 12: CSS Columns'},
  {value: './13_lesson/', label: 'Lesson 13: CSS Position'},
  {value: './14_lesson/', label: 'Lesson 14: CSS Flexbox'},
  {value: './15_lesson/', label: 'Lesson 15: CSS Grid'},
  {value: './16_lesson/', label: 'Lesson 16: CSS Images'},
  {value: './17_lesson/', label: 'Lesson 17: CSS Media Queries'},
  {value: './18_lesson/', label: 'Lesson 18: CSS Mini-Project: Profile Cards'},
  {value: './19_lesson/', label: 'Lesson 19: CSS Psuedo Selectors'},
  {value: './20_lesson/', label: 'Lesson 20: CSS Variables'},
  {value: './21_lesson/', label: 'Lesson 21: CSS Functions'},
  {value: './22_lesson/', label: 'Lesson 22: CSS Animations'},
  {value: './22_lesson/menu.html', label: 'Lesson 22: CSS Menu', style: 'menu'},
  {value: './23_lesson/', label: 'Lesson 23: BLock Element Modifier (BEM) Naming Convetion'},
  {value: './24_lesson/', label: 'Lesson 24: The Little Taco Shop'}
];
